# Generated by Django 3.2.9 on 2021-11-29 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_new_google_user',
            field=models.BooleanField(default=True, verbose_name='is new google user'),
        ),
    ]
