# Generated by Django 3.2.9 on 2021-12-20 17:04

import account.models
from django.db import migrations, models
import functools


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_follow_is_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_photo',
            field=models.ImageField(default=None, null=True, upload_to=functools.partial(account.models.save_image_path, *(), **{'is_background': True})),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default=None, null=True, upload_to=functools.partial(account.models.save_image_path, *(), **{'is_background': False})),
        ),
    ]
