# Generated by Django 3.2.9 on 2022-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20211220_1704'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='is_requested',
        ),
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='status of follow (0 - unfollow , 1 - requested , 2 - follow)'),
            preserve_default=False,
        ),
    ]
