# Generated by Django 3.2.9 on 2021-11-12 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import post.models
import utilities.display_name


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField(blank=True, max_length=1024, verbose_name='post caption')),
                ('media', models.ImageField(upload_to=post.models.save_post_path, verbose_name="post's media")),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='when post created')),
                ('display_name', models.CharField(default=utilities.display_name.post_display_name_maker, max_length=10, unique=True, verbose_name='post name for urls')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='when post updated')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="user's post")),
            ],
        ),
    ]
